services:
  - type: worker
    name: telegram-music-bot
    runtime: python
    region: singapore
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python bot.py"
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: MONGODB_URI
        sync: false
      - key: DB_NAME
        value: music_bot
      - key: ADMIN_IDS
        sync: false
      - key: CHANNEL_ID
        sync: false
